version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    volumes:
      - pgdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=jiglesia
      - POSTGRES_DB=piscineds
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
    networks:
      - default
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_LISTEN_PORT=4243
      - PGADMIN_DEFAULT_EMAIL=jiglesia@student.42.fr
      - PGADMIN_DEFAULT_PASSWORD=mysecretpassword
    ports:
      - 4243:4243
    networks:
      - default

volumes:
  pgdb:
    name: db
    driver: local

networks:
  default:
    driver: bridge