version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=jiglesia
      - POSTGRES_DB=piscineds
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432

volumes:
  postgres:
    name: postgresdb
